ALTER TABLE users
    ADD COLUMN IF NOT EXISTS notif_order_updates       BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notif_new_books           BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notif_subscription_alerts BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notif_promotions          BOOLEAN NOT NULL DEFAULT FALSE;
